// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

// https://astro.build/config
export default defineConfig({
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
  integrations: [
    starlight({
      routeMiddleware: "./src/routeData.ts",
      title: "Meantonal",
      logo: {
        src: "./src/assets/nav-logo.svg",
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/meantonal",
        },
      ],
      editLink: {
        baseUrl: "https://github.com/meantonal/documentation/blob/master/",
      },
      sidebar: [
        {
          label: "Start Here",
          autogenerate: { directory: "start" },
        },
        {
          label: "JS Reference",
          // Collapse the group and its autogenerated subgroups by default.
          collapsed: true,
          autogenerate: { directory: "js" },
        },
        {
          label: "C Reference",
          // Collapse the group and its autogenerated subgroups by default.
          collapsed: true,
          autogenerate: { directory: "c" },
        },
        {
          label: "Learn",
          autogenerate: { directory: "learn" },
        },
      ],
      components: {
        Header: "./src/components/Header.astro",
      },
      customCss: ["./src/styles/global.css"],
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
  site: "http://meantonal.org",
  output: "static",
});
